### ISSUE TITLE
Microsoft at ElectronConf

### ISSUE THREAD

**Issue by zeke** [felixrieseberg/electron-code-editor#5]
@felixrieseberg and I are planning to use this repo as the basis for a workshop at [ElectronConf](https://www.universe.com/events/electronconf-2017-tickets-29N48G)

@kieferrm from Microsoft has offered to help out on the workshop. I suggested that he and other attending MS folks roam around in the audience helping participants (as I will be doing).

If any of you have other thoughts about how best to contribute, I'm open to ideas!

cc @Tyriar @rebornix @chrmarti @roblourens

**Comment by felixrieseberg** [comment]
Oh hey, that's amazing! This essentially means that we can do this with a ton of attendees. We have a bit more time than we had for our first workshop, so we might want to add some meat at the end - I'm thinking about  `electron-forge`, native code, security, and updates/installations.

**Comment by kieferrm** [comment]
I guess you can close this one now. Anyway, we are happy to help if the opportunity rises again.

**Comment by zeke** [comment]
Sigh. Thanks 💛
